### ISSUE TITLE
Issue being used as a nested addon

### ISSUE THREAD

**Issue by nmcclay** [EmberSherpa/ember-element-resize-detector#3]
```
app.import is not a function
TypeError: app.import is not a function
    at Class.module.exports.included (/Users/nmcclay/git/light-table/node_modules/ember-light-table/node_modules/ember-element-resize-detector/index.js:20:17)
    at /Users/nmcclay/git/light-table/node_modules/ember-cli/lib/models/addon.js:244:32

```

I encountered this issue trying to upgrade [ember-light-table](https://github.com/offirgolan/ember-light-table) and noticed this problem.

```
    if (!process.env.EMBER_CLI_FASTBOOT) {
      app.import('vendor/element-resize-detector/element-resize-detector.js');
    }
```

**Comment by nmcclay** [comment]
Able to reproduce with ember 2.6 and a new addon project.

**Comment by nmcclay** [comment]
This issue seems directly related to this discussion about nested addons: https://github.com/ember-cli/ember-cli/issues/3718

Moving ember-light-table to a peerDependency seemed to resolve this issue... so I'm moving on.

**Comment by GCorbel** [comment]
@nmcclay I have the same issue but I'm contributing for [this addon](https://github.com/quantosobra/ember-data-table-light). I cannot add ember-light-table as peerDependency. Is there a solution?
